[toolchain]
channel = "nightly-2024-01-01"
components = [ "rustfmt", "rustc-dev", "clippy", "rust-src", "llvm-tools-preview" ]
targets = [ "x86_64-unknown-linux-gnu", "x86_64-pc-windows-gnu", "x86_64-unknown-none" ]
profile = "minimal"
